version: '3.8'
networks:
  mynetwork:
    driver: bridge

services:
  #mysql-container
  mysql-container:
    image: mysql:5.7
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot application service
  spring-app-container:
    image: iheb49/achat:latest
    container_name: spring-app-container
    restart: on-failure
    ports:
      - "8089:8089"
    networks:
      - mynetwork
    depends_on:
      - mysql-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/achatdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: 'true'
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: 'true'



#  achat-frontend:
#    image: iheb49/achat-front:lts
#    ports:
#      - "8085:80"
#    depends_on:
#      - mysql-container

  achat-frontend:
    image: iheb49/achat-front:lts
    ports:
      - "8085:80"
    depends_on:
      - mysql-container


volumes:
  mysql-data: