version: '3'

services:
  achat-backend:
    image: achat-spring-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/achatdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Mount a volume for MySQL data

